server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: zaqxsw2145


mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
  - classpath:mybatis/mapper/*.xml

logging:
  level:
    '[com.kkt.demo]': debug